version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    image: nayra000/simple_nodeapp:v1
    container_name: node_app_container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb_container:27017/employeesdb

volumes:
  mongo_data:
