- name: Install OpenJDK 17 and create Jenkins directory (Ubuntu)
  hosts: nodes
  tasks:

    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Create Jenkins directory
      file:
        path: /home/ubuntu/jenkins
        state: directory
        mode: '0755'

    - name: Verify Java installation
      command: java -version
      register: java_output
      ignore_errors: true

    - name: Display Java version
      debug:
        msg: |
          Stdout: {{ java_output.stdout | default('') }}
          Stderr: {{ java_output.stderr | default('') }}
